apiVersion: v1
kind: Service
metadata:
  name: new
  namespace: namespace-workflow-1692030991618
spec:
  type: LoadBalancer
  selector:
    app: new
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000